config/routes.rb
Rails.application.routes.draw do
  root 'viewer#index'

  get 'viewer/print' => 'viewer#print', as: :print_version
  get 'viewer/:id' => 'viewer#show', as: :viewer

  resources :sessions

  resources :vegetaux

  resources :familles

  get 'sign_in' => 'sessions#new', as: :sign_in
  get 'sign_out' => 'sessions#destroy', as: :sign_out

end

app/models/famille.rb
class Famille < ActiveRecord::Base
  default_scope { order('nom') }

  has_many :vegetable

end

app/models/vegetable.rb
class Vegetable < ActiveRecord::Base
  belongs_to :famille

  validates_presence_of :nom_commun, :classe, :genre, :espece
  validate :famille_chosen

  default_scope { includes(:famille).order('familles.nom').order('genre').order('espece') }

  has_attached_file :photo, styles: {
    thumb: '100x',
    medium: 'x400'
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  def nom
    full = []

    full << famille.nom unless famille.nil?
    full << genre unless genre.nil?
    full << espece unless espece.nil?

    if full.any?
      full.join(" ")
    else
      ""
    end
  end

  def famille_chosen
    errors.add(:famille_id, "You must select a Famille") unless famille_id.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :signed_in?

  private

  def authorize
    redirect_to sign_in_url, error: "Not authorized" if current_user.nil?
  end

  def current_user
    @current_user ||= session[:user] if session[:user]
  end

  def signed_in?
    current_user != nil
  end
end

app/controllers/familles_controller.rb
class FamillesController < ApplicationController
  before_filter :authorize, only: [:new, :edit, :update, :destroy]
  before_action :set_famille, only: [:show, :edit, :update, :destroy]

  # GET /familles
  # GET /familles.json
  def index
    @familles = Famille.all
  end

  # GET /familles/1
  # GET /familles/1.json
  def show
  end

  # GET /familles/new
  def new
    @famille = Famille.new
  end

  # GET /familles/1/edit
  def edit
  end

  # POST /familles
  # POST /familles.json
  def create
    @famille = Famille.new(famille_params)

    respond_to do |format|
      if @famille.save
        format.html { redirect_to @famille, notice: 'Famille was successfully created.' }
        format.json { render :show, status: :created, location: @famille }
      else
        format.html { render :new }
        format.json { render json: @famille.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /familles/1
  # PATCH/PUT /familles/1.json
  def update
    respond_to do |format|
      if @famille.update(famille_params)
        format.html { redirect_to @famille, notice: 'Famille was successfully updated.' }
        format.json { render :show, status: :ok, location: @famille }
      else
        format.html { render :edit }
        format.json { render json: @famille.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /familles/1
  # DELETE /familles/1.json
  def destroy
    @famille.destroy
    respond_to do |format|
      format.html { redirect_to familles_url, notice: 'Famille was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_famille
      @famille = Famille.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def famille_params
      params.require(:famille).permit(:nom)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController  
  def new
    respond_to do |format|
      format.html
      format.js { render layout: false, :content_type => 'text/html' }
    end
  end

  def create
    login = params[:login]
    password = params[:password]
    if (login == ENV['LOGIN_NAME'] && password == ENV['PASSWORD'])
      session[:user] = login
      begin
        redirect_to :back, :notice => "Signed in"
      rescue ActionController::RedirectBackError
        redirect_to root_path, :notice => "Signed in"
      end
    else
      flash.now[:error] = "Couldn't sign in with those details."
      render "new"
    end
  end

  def destroy
    session[:user] = nil
    redirect_to :back, notice: "Signed out"
    rescue ActionController::RedirectBackError
      redirect_to :root, notice: "Signed out"
  end
end

app/controllers/vegetaux_controller.rb
class VegetauxController < ApplicationController
  before_filter :authorize, only: [:new, :edit, :update, :destroy]
  before_action :set_vegetable, only: [:show, :edit, :update, :destroy]

  # GET /vegetaux
  # GET /vegetaux.json
  def index
    @vegetaux = Vegetable.all
  end

  # GET /vegetaux/1
  # GET /vegetaux/1.json
  def show
  end

  # GET /vegetaux/new
  def new
    @vegetable = Vegetable.new
  end

  # GET /vegetaux/1/edit
  def edit
  end

  # POST /vegetaux
  # POST /vegetaux.json
  def create
    @vegetable = Vegetable.new(vegetable_params)

    respond_to do |format|
      if @vegetable.save
        format.html { redirect_to @vegetable, notice: 'Vegetable was successfully created.' }
        format.json { render :show, status: :created, location: @vegetable }
      else
        format.html { render :new }
        format.json { render json: @vegetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vegetaux/1
  # PATCH/PUT /vegetaux/1.json
  def update
    respond_to do |format|
      if @vegetable.update(vegetable_params)
        format.html { redirect_to @vegetable, notice: 'Vegetable was successfully updated.' }
        format.json { render :show, status: :ok, location: @vegetable }
      else
        format.html { render :edit }
        format.json { render json: @vegetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vegetaux/1
  # DELETE /vegetaux/1.json
  def destroy
    @vegetable.destroy
    respond_to do |format|
      format.html { redirect_to vegetaux_url, notice: 'Vegetable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vegetable
      @vegetable = Vegetable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vegetable_params
      params.require(:vegetable).permit(:photo, :nom_commun, :famille_id, :classe, :genre, :espece, :origine_geographique, :cycle_biologique, :racine, :tige, :feuillage, :fleur, :fruit, :graine, :modes_de_multiplication_possibles, :systemes_de_production_adaptes, :mise_en_place_de_la_culture, :calendrier_cultural, :entretien_de_la_culture, :exigences_climatiques, :exigences_edaphiques_ideales, :irrigation, :fertilisation, :problemes_phytosanitaires_et_protections_adaptees, :importance_economique, :utilisation, :diversification)
    end
end

app/controllers/viewer_controller.rb
class ViewerController < ApplicationController
  before_action :set_vegetable, only: [:show]

  def index
    @vegetable = Vegetable.first
    nexter = Nexter.wrap( Vegetable.all, @vegetable )
    @previous = nexter.previous
    @next = nexter.next

    @first = @vegetable
    @last = Vegetable.last

    render 'show'
  end

  def show
    nexter = Nexter.wrap( Vegetable.all, @vegetable )
    @previous = nexter.previous
    @next = nexter.next

    @first = Vegetable.first
    @last = Vegetable.last
  end

  def print
    @vegetaux = Vegetable.all

    #puts @vegetaux.inspect

    respond_to do |format|
      format.html
      format.pdf do
        pdf = PrintPdf.new(@vegetaux)
        send_data pdf.render, filename: "vegetaux.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  private

    def set_vegetable
      @vegetable = Vegetable.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/familles_helper.rb
module FamillesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/vegetaux_helper.rb
module VegetauxHelper
end

app/helpers/viewer_helper.rb
module ViewerHelper
end

app/views/familles/_form.html.erb
<%= form_for(@famille) do |f| %>
  <% if @famille.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@famille.errors.count, "error") %> prohibited this famille from being saved:</h2>

      <ul>
      <% @famille.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %>
    <%= f.text_field :nom %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/familles/edit.html.erb
<h1>Editing famille</h1>

<%= render 'form' %>

<%= link_to 'Show', @famille, :class => 'button' %> |
<%= link_to 'Back to list', familles_path, :class => 'button' %>

app/views/familles/index.html.erb
<h1>Listing familles</h1>
<br>
<% unless current_user.nil?  %>
  <%= link_to 'New Famille', new_famille_path, :class => "button" %>
<% end %>

<table>
  <tbody>
    <% @familles.each do |famille| %>
      <tr>
        <td><%= famille.nom %></td>
        <% unless current_user.nil?  %>
          <td class="table-admin"><%= link_to 'Show', famille %> | <%= link_to 'Edit', edit_famille_path(famille) %> | <%= link_to 'Destroy', famille, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% unless current_user.nil?  %>
  <%= link_to 'New Famille', new_famille_path, :class => "button" %>
<% end %>

app/views/familles/new.html.erb
<h1>New famille</h1>

<%= render 'form' %>

app/views/familles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @famille.nom %>
</p>

<%= link_to 'Edit', edit_famille_path(@famille), :class => 'button' %> |
<%= link_to 'Back to list', familles_path, :class => 'button' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vegetaux</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="modal-window">
  <p>Something here</p>
</div>
<div id="modal-window-bg"></div>

<div class="main-content">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}", :class => "flash" %>
  <% end %>
  <%= yield %>
</div>

<footer class="site-footer">
  <div class="content">
    <p class="authentication-link">
      <% if signed_in? %>
        <%= link_to "Sign Out", sign_out_path %>
      <% else %>
        <%= link_to "Sign In", sign_in_path, class: "sign-in-link", remote: true %>
      <% end %>
    </p>

    <% if signed_in? %>
      <p><%= link_to "Viewer", root_path %> | <%= link_to "Familles", familles_path %> | <%= link_to "Vegetaux", vegetaux_path %> | <%= link_to "Print Version", print_version_path(format: "pdf") %></p>
    <% else %>
      <p><%= link_to "Reconnaissance des végétaux", root_path %> | <%= link_to "Print Version", print_version_path(format: "pdf") %></p>
    <% end %>
  </div>

</footer>

</body>
</html>

app/views/shared/_sign_in_form.html.erb
<section class="sign-in">
    <button type="button" class="modal-close">×</button>
    <h1>Sign In</h1>
    <div class="form-content">
      <%= form_tag sessions_path do %>
        <%= text_field_tag :login, params[:login], placeholder: :login, class: "form-input" %>
        <%= password_field_tag :password, params[:password], placeholder: :password, class: "form-input password" %>
        <%= submit_tag "Sign In", class: 'submit-button' %>
      <% end %>
    </div>
</section>

app/views/vegetaux/_form.html.erb
<%= form_for(@vegetable) do |f| %>
  <% if @vegetable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vegetable.errors.count, "error") %> prohibited this vegetable from being saved:</h2>

      <ul>
      <% @vegetable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :nom_commun %>
    <%= f.text_field :nom_commun %>
  </div>
  <div class="field">
    <%= f.label :famille_id %>
    <%= collection_select(:vegetable, :famille_id, Famille.all, :id, :nom, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :classe %>
    <%= f.text_field :classe %>
  </div>
  <div class="field">
    <%= f.label :genre %>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :espece %>
    <%= f.text_field :espece %>
  </div>
  <div class="field">
    <%= f.label :origine_geographique %>
    <%= f.text_field :origine_geographique %>
  </div>
  <div class="field">
    <%= f.label :cycle_biologique %>
    <%= f.text_field :cycle_biologique %>
  </div>
  <div class="field">
    <%= f.label :racine %>
    <%= f.text_field :racine %>
  </div>
  <div class="field">
    <%= f.label :tige %>
    <%= f.text_field :tige %>
  </div>
  <div class="field">
    <%= f.label :feuillage %>
    <%= f.text_field :feuillage %>
  </div>
  <div class="field">
    <%= f.label :fleur %>
    <%= f.text_field :fleur %>
  </div>
  <div class="field">
    <%= f.label :fruit %>
    <%= f.text_field :fruit %>
  </div>
  <div class="field">
    <%= f.label :graine %>
    <%= f.text_field :graine %>
  </div>
  <div class="field">
    <%= f.label :modes_de_multiplication_possibles %>
    <%= f.text_field :modes_de_multiplication_possibles %>
  </div>
  <div class="field">
    <%= f.label :systemes_de_production_adaptes %>
    <%= f.text_field :systemes_de_production_adaptes %>
  </div>
  <div class="field">
    <%= f.label :mise_en_place_de_la_culture %>
    <%= f.text_field :mise_en_place_de_la_culture %>
  </div>
  <div class="field">
    <%= f.label :calendrier_cultural %>
    <%= f.text_field :calendrier_cultural %>
  </div>
  <div class="field">
    <%= f.label :entretien_de_la_culture %>
    <%= f.text_field :entretien_de_la_culture %>
  </div>
  <div class="field">
    <%= f.label :exigences_climatiques %>
    <%= f.text_field :exigences_climatiques %>
  </div>
  <div class="field">
    <%= f.label :exigences_edaphiques_ideales %>
    <%= f.text_field :exigences_edaphiques_ideales %>
  </div>
  <div class="field">
    <%= f.label :irrigation %>
    <%= f.text_field :irrigation %>
  </div>
  <div class="field">
    <%= f.label :fertilisation %>
    <%= f.text_field :fertilisation %>
  </div>
  <div class="field">
    <%= f.label :problemes_phytosanitaires_et_protections_adaptees %>
    <%= f.text_field :problemes_phytosanitaires_et_protections_adaptees %>
  </div>
  <div class="field">
    <%= f.label :importance_economique %>
    <%= f.text_field :importance_economique %>
  </div>
  <div class="field">
    <%= f.label :utilisation %>
    <%= f.text_field :utilisation %>
  </div>
  <div class="field">
    <%= f.label :diversification %>
    <%= f.text_field :diversification %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vegetaux/edit.html.erb
<h1>Editing vegetable</h1>

<%= render 'form' %>

<br>

<%= link_to 'Show', @vegetable %> |
<%= link_to 'Back to list', vegetaux_path %>

app/views/vegetaux/index.html.erb
<h1>Listing vegetaux</h1>
<br>
<% unless current_user.nil?  %>
  <%= link_to 'New Vegetable', new_vegetable_path, :class => "button" %>
<% end %>
<table>

  <tbody>
    <% @vegetaux.each do |vegetable| %>
      <tr>
        <td class="table-image"><%= image_tag vegetable.photo.url(:thumb) %></td>
        <td class="table-nom"><%= vegetable.nom %></td>
        <td class="table-nom-commun"><%= vegetable.nom_commun %></td>
        <% unless current_user.nil?  %>
          <td class="table-admin"><%= link_to 'Show', vegetable %> | <%= link_to 'Edit', edit_vegetable_path(vegetable) %> | <%= link_to 'Destroy', vegetable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% unless current_user.nil?  %>
  <%= link_to 'New Vegetable', new_vegetable_path, :class => "button" %>
<% end %>

app/views/vegetaux/new.html.erb
<h1>New vegetable</h1>

<%= render 'form' %>

app/views/vegetaux/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New Vegetable', new_vegetable_path, :class => "button" %>

<br>
<br>

<p><%= image_tag @vegetable.photo.url(:medium) %></p>

<p>
  <strong>Nom commun:</strong>
  <%= @vegetable.nom_commun %>
</p>

<p>
  <strong>Famille:</strong>
  <% unless @vegetable.famille.nil? %>
    <%= @vegetable.famille.nom %>
  <% end %>
</p>

<p>
  <strong>Classe:</strong>
  <%= @vegetable.classe %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @vegetable.genre %>
</p>

<p>
  <strong>Espece:</strong>
  <%= @vegetable.espece %>
</p>

<p>
  <strong>Origine geographique:</strong>
  <%= @vegetable.origine_geographique %>
</p>

<p>
  <strong>Cycle biologique:</strong>
  <%= @vegetable.cycle_biologique %>
</p>

<p>
  <strong>Racine:</strong>
  <%= @vegetable.racine %>
</p>

<p>
  <strong>Tige:</strong>
  <%= @vegetable.tige %>
</p>

<p>
  <strong>Feuillage:</strong>
  <%= @vegetable.feuillage %>
</p>

<p>
  <strong>Fleur:</strong>
  <%= @vegetable.fleur %>
</p>

<p>
  <strong>Fruit:</strong>
  <%= @vegetable.fruit %>
</p>

<p>
  <strong>Graine:</strong>
  <%= @vegetable.graine %>
</p>

<p>
  <strong>Modes de multiplication possibles:</strong>
  <%= @vegetable.modes_de_multiplication_possibles %>
</p>

<p>
  <strong>Systemes de production adaptes:</strong>
  <%= @vegetable.systemes_de_production_adaptes %>
</p>

<p>
  <strong>Mise en place de la culture:</strong>
  <%= @vegetable.mise_en_place_de_la_culture %>
</p>

<p>
  <strong>Calendrier cultural:</strong>
  <%= @vegetable.calendrier_cultural %>
</p>

<p>
  <strong>Entretien de la culture:</strong>
  <%= @vegetable.entretien_de_la_culture %>
</p>

<p>
  <strong>Exigences climatiques:</strong>
  <%= @vegetable.exigences_climatiques %>
</p>

<p>
  <strong>Exigences edaphiques ideales:</strong>
  <%= @vegetable.exigences_edaphiques_ideales %>
</p>

<p>
  <strong>Irrigation:</strong>
  <%= @vegetable.irrigation %>
</p>

<p>
  <strong>Fertilisation:</strong>
  <%= @vegetable.fertilisation %>
</p>

<p>
  <strong>Problemes phytosanitaires et protections adaptees:</strong>
  <%= @vegetable.problemes_phytosanitaires_et_protections_adaptees %>
</p>

<p>
  <strong>Importance economique:</strong>
  <%= @vegetable.importance_economique %>
</p>

<p>
  <strong>Utilisation:</strong>
  <%= @vegetable.utilisation %>
</p>

<p>
  <strong>Diversification:</strong>
  <%= @vegetable.diversification %>
</p>

<%= link_to 'Edit', edit_vegetable_path(@vegetable), :class => 'button' %> |
<%= link_to 'Back to list', vegetaux_path, :class => 'button' %> |
<%= link_to 'New Vegetable', new_vegetable_path, :class => "button" %>

app/views/viewer/_list_item.html.erb
<li><span class="item-label"><%= list_item[:label] %></span><span class="item-content"><%= list_item[:content] %></span></li>

app/views/viewer/print.html.erb
<ul>
<% @vegetaux.each do |vegetable| %>
  <li><%= vegetable.nom_commun %></li>
<% end %>
</ul>

app/views/viewer/show.html.erb
<% @botaniques = [
  { label: "Origine géographique – milieu naturel", content: @vegetable.origine_geographique },
  { label: "Cycle biologique", content: @vegetable.cycle_biologique },
  { label: "Racine", content: @vegetable.racine },
  { label: "Tige", content: @vegetable.tige },
  { label: "Feuillage", content: @vegetable.feuillage },
  { label: "Fleur", content: @vegetable.fleur },
  { label: "Fruit", content: @vegetable.fruit },
  { label: "Graine", content: @vegetable.graine }
] %>

<% @techniques = [
  { label: "Modes de multiplication possibles", content: @vegetable.modes_de_multiplication_possibles },
  { label: "Systèmes de productions adaptés", content: @vegetable.systemes_de_production_adaptes },
  { label: "Mise en place de la culture", content: @vegetable.mise_en_place_de_la_culture },
  { label: "Calendrier cultural", content: @vegetable.calendrier_cultural },
  { label: "Entretien de la culture", content: @vegetable.entretien_de_la_culture },
  { label: "Exigences climatiques", content: @vegetable.exigences_climatiques },
  { label: "Exigences édaphiques (idéales)", content: @vegetable.exigences_edaphiques_ideales },
  { label: "Irrigation", content: @vegetable.irrigation },
  { label: "Fertilisation", content: @vegetable.fertilisation },
  { label: "Problèmes phytosanitaires et protections adaptées", content: @vegetable.problemes_phytosanitaires_et_protections_adaptees },
  { label: "Importance économique", content: @vegetable.importance_economique },
  { label: "Utilisation", content: @vegetable.utilisation },
  { label: "Diversification (variétés, cultivars…)", content: @vegetable.diversification } 
] %>

<section class="viewer-header">
  <div class="main-image"><%= image_tag @vegetable.photo.url(:medium) %></div>
  <div class="main-heading">
    <h1><%= @vegetable.nom %></h1>
    <h4>or</h4>
    <h2><%= @vegetable.nom_commun %></h2>
  </div>
</section>

<section class="viewer-content">
  <h2>Caractéristiques Botaniques</h2>
  <ul>
    <%= render partial: "list_item", collection: @botaniques %>
  </ul>
</section>

<section class="viewer-content">
  <h2>Caractéristiques Techniques et Culturales</h2>
  <ul>
    <%= render partial: "list_item", collection: @techniques %>
  </ul>
</section>

<section class="navigation">
  <div class="nav-link previous">
    <% unless @previous.nil? %>
      <h3><%= link_to "← Previous", viewer_path(@previous.id), data: { keybinding: 'left' } %></h3>
    <% else %>
      <h3><%= link_to "← Last", viewer_path(@last.id), data: { keybinding: 'left' } %></h3>
    <% end %>
  </div>

  <div class="nav-link next">
    <% unless @next.nil? %>
      <h3><%= link_to "Next →", viewer_path(@next.id), data: { keybinding: 'right' } %></h3>
    <% else %>
      <h3><%= link_to "First →", viewer_path(@first.id), data: { keybinding: 'right' } %></h3>
    <% end %>
  </div>
</section>

<div class="help">
  <p>You can also press the &larr; &amp; &rarr; keys to navigate.</p>
</div>